export type MemoryCategory = 
  | 'mission' 
  | 'goal' 
  | 'decision' 
  | 'task_completed' 
  | 'task_pending' 
  | 'document' 
  | 'research' 
  | 'external_conversation' 
  | 'meeting_summary' 
  | 'approval' 
  | 'timeline_event';

export interface ProjectMemoryEntry {
  id: string;
  projectId: string;
  category: MemoryCategory;
  agentId?: string;
  agentName?: string;
  title: string;
  content: string;
  createdAt: number;
  metadata?: Record<string, unknown>;
}

export interface ProjectMemory {
  projectId: string;
  entries: ProjectMemoryEntry[];
  summary: string; // Dynamic summary of the project state generated by Architect
  lastUpdated: number;
}
